// Generated by CoffeeScript 2.7.0
(function() {
  var provider;

  provider = require('./provider');

  module.exports = {
    config: {
      ignoreMooseNotFoundError: {
        type: 'boolean',
        default: false,
        description: 'Suppress error popups if no MOOSE executable is found.'
      },
      allowTestObjects: {
        type: 'boolean',
        default: true,
        description: 'Show test objects in the suggestion list.'
      },
      hideDeprecatedParams: {
        type: 'boolean',
        default: true,
        description: 'Hide deprecated parameters in the suggestion list.'
      },
      fallbackMooseDir: {
        type: 'string',
        default: '',
        description: 'If no MOOSE executable is found in or above the current directory, search here instead.'
      },
      offlineSyntax: {
        type: 'string',
        default: '',
        description: 'Specify a filename of a JSON dump generated by manually running `./my_moose_app-opt --json > syntax.txt`. This can be useful for writing input files on a machine without MOOSE available.'
      }
    },
    activate: function(state) {
      atom.commands.add('atom-workspace', 'autocomplete-moose:clear-cache', () => {
        return provider.clearCache();
      });
      // avoid requerying frequently used config items
      provider.offlineSyntax = atom.config.get('autocomplete-moose.offlineSyntax');
      atom.config.onDidChange('autocomplete-moose.offlineSyntax', function({newValue, oldValue}) {
        return provider.offlineSyntax = newValue;
      });
      provider.hideDeprecatedParams = atom.config.get('autocomplete-moose.hideDeprecatedParams');
      return atom.config.onDidChange('autocomplete-moose.hideDeprecatedParams', function({newValue, oldValue}) {
        return provider.hideDeprecatedParams = newValue;
      });
    },
    getProvider: function() {
      return provider;
    }
  };

}).call(this);
